name: Windows Debug

on:
  workflow_dispatch:

jobs:
  windows:
    name: Windows x64
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      PREPARE_PATH: Telegram/build/prepare/prepare.py

    defaults:
      run:
        shell: cmd

    steps:
      - name: Prepare directories
        run: |
          mkdir %userprofile%\TBuild\Libraries
          mklink /d %GITHUB_WORKSPACE%\TBuild %userprofile%\TBuild
          echo TBUILD=%GITHUB_WORKSPACE%\TBuild>>%GITHUB_ENV%
          echo LibrariesPath=%GITHUB_WORKSPACE%\TBuild\Libraries\win64>>%GITHUB_ENV%

      - name: Set repository name
        shell: bash
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> "$GITHUB_ENV"

      - name: Clone
        uses: actions/checkout@v7
        with:
          submodules: recursive
          path: ${{ env.TBUILD }}\${{ env.REPO_NAME }}

      - name: Read build configuration
        shell: bash
        run: |
          DOCPATH="$TBUILD/$REPO_NAME/docs/building-win.md"
          SDK="$(grep 'SDK version' "$DOCPATH" | sed -r 's/.*\*\*(.*)\*\* SDK version.*/\1/')"
          echo "SDK=$SDK" >> "$GITHUB_ENV"
          sed -i '/CMAKE_${lang}_FLAGS_DEBUG_INIT/s/${_Zi}//' "$PROGRAMFILES"/CMake/share/cmake*/Modules/Platform/Windows-MSVC.cmake
          {
            sha256sum "$TBUILD/$REPO_NAME/$PREPARE_PATH"
            echo "$SDK"
          } > CACHE_KEY.txt
          echo "CACHE_KEY=$(sha256sum CACHE_KEY.txt | awk '{ print $1 }')" >> "$GITHUB_ENV"

      - name: Native Tools Command Prompt
        uses: Eden-CI/msvc-dev-cmd@1bd71f95d6f3d1b2b3395b335cc63bcdc90cf223
        with:
          arch: x64
          sdk: ${{ env.SDK }}
          toolset: 14.44

      - name: Configure NuGet sources
        run: |
          nuget sources Disable -Name "Microsoft Visual Studio Offline Packages"
          nuget sources Add -Source https://api.nuget.org/v3/index.json & exit 0

      - name: Restore ThirdParty cache
        uses: actions/cache@v6
        with:
          path: ${{ env.TBUILD }}\ThirdParty
          key: ${{ runner.os }}-${{ runner.arch }}-third-party-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.os }}-${{ runner.arch }}-third-party-

      - name: Restore libraries cache
        uses: actions/cache@v6
        with:
          path: |
            ${{ env.LibrariesPath }}\*
            !${{ env.LibrariesPath }}\cache_keys
            !${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\*
            !${{ env.LibrariesPath }}\cache_keys\[qQ]t[_-]*
          key: ${{ runner.os }}-x64-libs-v2-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.os }}-x64-libs-v2-

      - name: Restore Qt cache
        uses: actions/cache@v6
        with:
          path: |
            ${{ env.LibrariesPath }}\[qQ]t[_-]*
            ${{ env.LibrariesPath }}\cache_keys\[qQ]t[_-]*
          key: ${{ runner.os }}-x64-qt-${{ env.CACHE_KEY }}
          restore-keys: ${{ runner.os }}-x64-qt-

      - name: Prepare libraries
        run: '%TBUILD%\%REPO_NAME%\Telegram\build\prepare\win.bat skip-release silent'

      - name: Free disk space
        shell: bash
        run: find "$LibrariesPath" '(' '(' ! '(' -name '*.lib' -o -name '*.a' -o -name '*.exe' -o -name '*.h' -o -name '*.hpp' -o -name '*.inc' -o -name '*.cmake' -o -name '*.pc' -o -path '*/include/*' -o -path '*/objects-*' -o -path '*/cache_keys/*' -o -path '*/patches/*' -o -path '*/nv-codec-headers/*' ')' -type f ')' -o -empty ')' -delete

      - name: Build AyuGram Desktop
        run: |
          cd %TBUILD%\%REPO_NAME%\Telegram
          call configure.bat ^
          x64 ^
          -D TDESKTOP_API_TEST=ON ^
          -D CMAKE_CONFIGURATION_TYPES=Debug ^
          -D CMAKE_COMPILE_WARNING_AS_ERROR=ON ^
          -D CMAKE_MSVC_DEBUG_INFORMATION_FORMAT= ^
          -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON
          cmake --build ..\out --config Debug --parallel

      - name: Check output
        run: |
          if not exist %TBUILD%\%REPO_NAME%\out\Debug\AyuGram.exe exit /b 1
          if not exist %TBUILD%\%REPO_NAME%\out\Debug\Updater.exe exit /b 1
          dir %TBUILD%\%REPO_NAME%\out\Debug\AyuGram.exe
          dir %TBUILD%\%REPO_NAME%\out\Debug\Updater.exe

      - name: Prepare artifact
        run: |
          mkdir artifact
          move %TBUILD%\%REPO_NAME%\out\Debug\AyuGram.exe artifact\
          move %TBUILD%\%REPO_NAME%\out\Debug\Updater.exe artifact\

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: AyuGram-Windows-x64-Debug
          path: artifact\
          retention-days: 7
